### ISSUE TITLE
Roadmap to rez 3.0

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [AcademySoftwareFoundation/rez#1558]
This issue tracks the roadmap I have in mind for a 3.0 release of rez. I don't think anythng that I included will be or is controversial. I tried to keep it as conservative as possible.

```[tasklist]
### 2.114.0 (last release in the 2.x series)
- [ ] https://github.com/AcademySoftwareFoundation/rez/pull/1550
- [ ] https://github.com/AcademySoftwareFoundation/rez/pull/1469
- [ ] https://github.com/AcademySoftwareFoundation/rez/pull/1534
- [x] Deprecated rez 1 compatibility settings so that we can remove them in the future
- [x] Mark anything in https://github.com/AcademySoftwareFoundation/rez/issues/1552 that is not yet marked as deprecated, as deprecated.
```
(see the [2.114.0 milestone](https://github.com/AcademySoftwareFoundation/rez/milestone/3))

```[tasklist]
### 3.0.0
- [ ] https://github.com/AcademySoftwareFoundation/rez/issues/1551
- [ ] https://github.com/AcademySoftwareFoundation/rez/issues/1553
- [ ] https://github.com/AcademySoftwareFoundation/rez/issues/1561
- [x] Remove rez.vendor.version
- [ ] https://github.com/AcademySoftwareFoundation/rez/pull/1475
- [ ] https://github.com/AcademySoftwareFoundation/rez/pull/1536
```
(see the [3.0.0 milestone](https://github.com/AcademySoftwareFoundation/rez/milestone/4))
