### ISSUE TITLE
Remove all traces of Python 2

### ISSUE THREAD

**Issue by JeanChristopheMorinPerso** [AcademySoftwareFoundation/rez#1635]
Support for Python 2 was removed in 3.0.0, but we left some leftovers. This issue lists what's left to be done to really remove all traces of Python 2 from the codebase.

```[tasklist]
### Tasks
- [x] Remove `rez.backport`
- [ ] https://github.com/AcademySoftwareFoundation/rez/issues/1646
- [ ] https://github.com/AcademySoftwareFoundation/rez/issues/1648
- [ ] https://github.com/AcademySoftwareFoundation/rez/issues/1637
- [ ] https://github.com/AcademySoftwareFoundation/rez/issues/1833
- [ ] https://github.com/AcademySoftwareFoundation/rez/issues/1636
- [ ] Look at PRs/commits that added support for Python 3 and see if we missed anything
- [ ] Run https://github.com/asottile/pyupgrade
```

If you want to start working on one of these task and it's not yet converted to an issue, please comment in the issue and we will happily create an issue.

<details><summary>List of Python 2 to 3 PRs</summary>

Note that there is a lot of noise in these PRs. But they can be used to see what kind of compatibility layers were added to support both python 2 and 3. This will be handy to determine if something should be removed.

* https://github.com/AcademySoftwareFoundation/rez/pull/736
* https://github.com/AcademySoftwareFoundation/rez/pull/740
* https://github.com/AcademySoftwareFoundation/rez/pull/742
* https://github.com/AcademySoftwareFoundation/rez/pull/745
* https://github.com/AcademySoftwareFoundation/rez/pull/753
* https://github.com/AcademySoftwareFoundation/rez/pull/766
* https://github.com/AcademySoftwareFoundation/rez/pull/733
* https://github.com/AcademySoftwareFoundation/rez/pull/743
* https://github.com/AcademySoftwareFoundation/rez/pull/727
* https://github.com/AcademySoftwareFoundation/rez/pull/755
* https://github.com/AcademySoftwareFoundation/rez/pull/725
* https://github.com/AcademySoftwareFoundation/rez/pull/713
* https://github.com/AcademySoftwareFoundation/rez/pull/712
* https://github.com/AcademySoftwareFoundation/rez/pull/710
</details>

**Comment by hww-nikhilshankarnoble** [comment]
@JeanChristopheMorinPerso has anyone picked up the removal of `rez.utils.py23` task yet? I was looking for a straightforward task to kickstart hopefully contributing to Rez more in the future, and would like to pick it up if not :)

**Comment by JeanChristopheMorinPerso** [comment]
@hww-nikhilshankarnoble I don't think so. I have created https://github.com/AcademySoftwareFoundation/rez/issues/1646 if you want to work on it.

**Comment by lbreede** [comment]
@JeanChristopheMorinPerso has anyone tackled these magic methods yet?
> Remove/replace all deprecated (python 2) magic methods (__<method>__)

I may look into that as part of the Dev Days 2024.

**Comment by JeanChristopheMorinPerso** [comment]
Hi @lbreede . I don't think anyone did that. Feel free to give it a try. But note that rez is not participating to the dez days and as such we might not be able to review your contributions in time. We still appreciate all contributions, so please do contribute if you can. We might be slow to review though.

**Comment by lbreede** [comment]
@JeanChristopheMorinPerso, I may just tackle it regardless. Is there an issue for this specific task yet?

**Comment by JeanChristopheMorinPerso** [comment]
@lbreede I just created https://github.com/AcademySoftwareFoundation/rez/issues/1833.

**Comment by JeanChristopheMorinPerso** [comment]
I think we are finally done with this. I'm satisfied with the state of things. I'll close this.
